# Generated by Django 3.2.7 on 2022-05-11 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfDestory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.UUIDField(default=uuid.UUID('5d8bca0f-2c99-4639-b888-03aad16ccf7f'))),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('key', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('destory_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.selfdestory')),
            ],
        ),
    ]
