# Generated by Django 3.2.7 on 2022-05-11 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='web_id',
            field=models.UUIDField(default=uuid.UUID('0c98dba1-fc46-4f8d-9ca9-cc5e8c1d1152')),
        ),
    ]
