# Generated by Django 3.2.7 on 2022-05-11 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_web_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
        migrations.RemoveField(
            model_name='selfdestory',
            name='count',
        ),
        migrations.AlterField(
            model_name='note',
            name='web_id',
            field=models.UUIDField(default=uuid.UUID('2748ead2-ca8a-4b26-90fd-c51d5b777ff6')),
        ),
    ]
