# Generated by Django 3.2.7 on 2022-05-11 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20220511_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='note',
            name='web_id',
            field=models.UUIDField(default=uuid.UUID('52a049a1-8562-4ce9-8aef-c8179bb8889e')),
        ),
    ]
