# Generated by Django 3.2.7 on 2022-05-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_web_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfdestory',
            name='is_destroy',
            field=models.BooleanField(default=False),
        ),
    ]
