# Generated by Django 3.2.7 on 2022-05-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_selfdestory_is_destroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='confirmation',
            new_name='is_destroy',
        ),
        migrations.RemoveField(
            model_name='selfdestory',
            name='is_destroy',
        ),
    ]
